config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :filters
  resources :notifications
  resources :profiles, only: [:show]
  resources :reports, only: [:index, :new, :create]

  get 'search/index'

  resources :tags, only: [:index, :show]
  resources :images do
    get 'comments'
    put 'update_metadata'
    resources :comments
  end

  namespace :pages do
    get 'activity'
    get 'notifications'
  end

  get '/comments', action: :index, controller: :comments

  root to: 'pages#activity'
  get '*path', controller: 'pages', action: 'render_404'
end

app/models/image.rb
class Image < ActiveRecord::Base
  include AnonymizableUserAttributable
  include FancySearchable
  include Indexable
  include Interactable
  include Notifyable
  include Reportable

  has_attached_file :image, presence: true, styles: {thumb_tiny: '50x50>', thumb_small: '150x150>', thumb: '250x250>', small: '320x240>', medium: '800x600>', large: '1280x1024>', tall: '1024x4096>'}

  # Validations
  validates_attachment :image, content_type: {content_type: %w|image/png image/jpeg image/gif|}, size: {in: 0..25000.kilobytes}, presence: true
  validates :id_number, uniqueness: true, presence: true

  ALLOWED_PARAMETERS = [:description, :image, :source_url, :tag_list]

  # Relations
  has_array_field :tags
  has_many :comments, validate: false
  belongs_to :user, inverse_of: :images
  belongs_to :hidden_by_user, class_name: 'User', inverse_of: :hidden_images

  # Callbacks
  before_validation do
    if not self.persisted?
      last_image = Image.order(id_number: :desc).select(:id_number).first
      if last_image and last_image.id_number and last_image.id_number >= 0
        self.id_number = last_image.id_number+1
      else
        self.id_number = 0
      end
    end
  end

  before_save :extract_dimensions

  def to_param
    id_number.to_s
  end

  def tag_list=(tag_list)
    set_tag_list(tag_list)
  end

  def tag_list
    @tag_list ||= self.tags.map(&:name).join(',')
  end

  def set_tag_list(new_tag_list)
    old_tags = self.tags.to_a
    new_tags = Tag.tag_string_to_tags(new_tag_list)

    # Any tags we didn't previously have
    (new_tags - old_tags).each do |t|
      t.decrement!(:image_count)
      t.update_index
    end

    # Tags that were removed
    (old_tags - new_tags).each do |t|
      t.decrement!(:image_count)
      t.update_index
    end

    self.tag_ids = new_tags.map(&:id)
    @tag_list = new_tags.map(&:name).join(',')
  end

  def tags
    Tag.where(id: self.tag_ids)
  end

  # Callback to retreieve dimension metadata about a file.
  def extract_dimensions
    tempfile = image.queued_for_write[:original]
    unless tempfile.nil?
      geometry = Paperclip::Geometry.from_file(tempfile)
      self.dimensions = [geometry.width.to_i, geometry.height.to_i].join('x')
    end
  end

  # Elasticsearch
  def as_json(options = {})
    d = {
      id: self.id.to_s,
      id_number: self.id_number,
      created_at: self.created_at,
      updated_at: self.updated_at,
      description: self.description,
      hidden_from_users: self.hidden_from_users,
      comment_count: self.comment_count,
      source_url: self.source_url,
      tag_ids: self.tags.map{|t| t.id.to_s},
      tag_names: self.tags.map(&:name),
      uploader: self.author.try(:name).to_s,
    }
  end

  def as_indexed_json(options = {})
    d = self.as_json(options)
    d[:ip] = self.ip.to_s
    d[:uploader_id] = self.user_id.to_s
    return d
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false', _all: {enabled: false} do
      indexes :id, type: 'integer', index: 'not_analyzed'
      indexes :id_number, type: 'integer', index: 'not_analyzed'
      indexes :hidden_from_users, type: 'boolean', index: 'not_analyzed'
      indexes :created_at, type: 'date'
      indexes :updated_at, type: 'date'
      indexes :description, type: 'string', analyzer: 'snowball'
      indexes :ip, type: 'string', index: 'not_analyzed'
      indexes :source_url, type: 'string', index: 'not_analyzed'
      indexes :tag_ids, type: 'string', index: 'not_analyzed'
      indexes :tag_names, type: 'string', index: 'not_analyzed'
      indexes :uploader, type: 'string', index: 'not_analyzed'
      indexes :uploader_id, type: 'integer', index: 'not_analyzed'
    end
  end

  def self.default_sort
    [{:created_at => :desc}]
  end

  def self.default_field
    :tag_names
  end

  def self.allowed_fields(options = {})
    [:id, :id_number, :description, :source_url, :tag_names, :uploader]
  end

  def self.fancy_search(options = {}, &block)
    super(options) do |s|
      yield s if block

      # Filter hidden tags
      if not options[:hidden_tag_ids].blank?
        s.add_filter(not: {terms: {tag_ids: options[:hidden_tag_ids], _cache: true}})
      end

      # Hidden complex
      if not options[:hidden_complex].blank?
        parser = Image.get_search_parser.call(options[:hidden_complex], options)
        if parser.requires_query
          s.add_filter(fquery: {query: {bool: {must_not: parser.parsed}, _cache: true}})
        else
          s.add_filter(not: parser.parsed.merge(_cache: true))
        end
      end
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images_search = Image.fancy_search(default_image_filter_options.merge(size: 25)) do |search|
      search.add_sort :created_at, :desc
    end
    @images = @images_search.records
  end

  def show
    @image = Image.find_by(id_number: params[:id])
    render_404_if_not(@image) do
      @comments = @image.comments.order(created_at: :desc).limit(25)
      render layout: 'image'
    end
  end

  def comments
    @image = Image.find_by(id_number: params[:id])
    @comments = @image.comments.order(created_at: :desc).limit(25)
  end

  def update_metadata
    @image = Image.find_by(id_number: params[:image_id])
    render_404_if_not(@image) do
      @image.set_tag_list(params[:tag_list])
      render partial: 'images/tags_source', layout: false
    end
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params.require(:image).permit(Image::ALLOWED_PARAMETERS))
    @image.capture!(current_user, request)
    if @image.save
      redirect_to image_path(@image)
    else
      render action: 'new'
    end
  end
end

app/views/images/_form.html.slim
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      h2= "#{pluralize(@image.errors.count, 'error')} prevented this from being uploaded:"
      ul
        - @image.errors.full_messages.each do |msg|
          li= msg
  .field
    => f.label :image, 'Upload Image'
    => f.file_field :image
  .field
    = f.text_field :source_url, placeholder: 'Source URL'
  .field
    = f.text_area :tag_list, class: 'fancy-tags', placeholder: 'Tags'
  .field
    = f.text_area :description, placeholder: :description
  .actions
    = f.submit data:{disable_with: 'Please wait...'}

app/views/images/_image_list.html.slim
- for i in images
  .thumb.thumb-normal
    a href=image_path(i)
      .block=<> image_tag i.image.url(:thumb)

app/views/images/_tags_source.html.slim
#image-tags
  = render partial: 'tags/tag_list', locals: {tags: @image.tags.order(system: :desc, name: :asc)[0..9]}
- if not @image.source_url.blank?
  #image-source
    = link_to truncate(@image.source_url, length: 500), @image.source_url
  #update-metadata style="display:none"
    = form_tag image_update_metadata_path(@image), method: :put, remote: true, id: 'image_metadata_form' do
      = hidden_field_tag :old_tag_list, @image.tag_list
      .field= text_area_tag :tag_list, @image.tag_list, class: 'fancy-tags'
      .field= text_field_tag :source_url, @image.source_url
      .actions= submit_tag "Save Tags and Source"

app/views/images/index.html.slim
h2 New Images
br
- for i in @images
  a href=image_path(i)
    =<> image_tag i.image.url(:thumb)

app/views/images/new.html.slim
h2 New image
br
= render partial: 'images/form'

app/views/images/show.html.slim
#image-container
  = image_tag @image.image.url(:large)
#image-metadata
  = render partial: 'images/tags_source'
#image-actions
  ul#image-menu
    li
      a#edit-tags href="#"
        i.fa.fa-pencil
    li
      a#download-image href=@image.image.url
        i.fa.fa-download
#comment-form
  - @comment = Comment.new
  = render partial: 'comments/form'
#image-comments
  - if @comments.count > 0
    = render partial: 'comments/image_comments', locals: {comments: @comments}