config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :filters
  resources :notifications
  resources :profiles, only: [:show]
  resources :reports, only: [:index, :new, :create]

  get 'search/index'

  resources :tags, only: [:index, :show]
  resources :images do
    get 'comments'
    put 'update_metadata'
    resources :comments
  end

  namespace :pages do
    get 'activity'
    get 'notifications'
  end

  get '/comments', action: :index, controller: :comments

  root to: 'pages#activity'
  get '*path', controller: 'pages', action: 'render_404'
end

app/views/layouts/_header.html.slim
#header
  #left
    span
      a#home href="/" Litebooru
      a#upload< href=new_image_path
        i.fa.fa-fw.fa-upload
    span
      = form_tag(search_index_path, method: :get) do
        = text_field_tag :q, (@query or (@tag.try(:name))).to_s, placeholder: 'Search'
  #right
    - if user_signed_in?
      span
        a#notifications href=pages_notifications_path
          i.fa.fa-bell
      span.dropdown-container.sw
        a.dropdown-icon.profile href="#"
          = image_tag current_user.avatar.url(:small), size: '20x20', class: 'avatar-img'
          i.fa.fa-caret-down<
        .dropdown-menu
          ul
            li
              a href=profile_path(current_user)
                i.fa.fa-user>
                = current_user.name
            li
              a href=edit_user_registration_path
                i.fa.fa-wrench>
                | Account
            li
              a href=destroy_user_session_path data-method="delete" data-confirm=t('are_you_sure') rel="nofollow"
                i.fa.fa-sign-out>
                | Sign out
    - else
      span
        = form_tag(new_user_session_path, method: :get) do
          = submit_tag "Login"
#subheader
  a class=images_subheader_class href=images_path Images
  a class=activity_subheader_class href='/' Activity
  a class=tags_subheader_class href=tags_path Tags

app/views/layouts/application.html.slim
doctype html
html
  head
    title Litebooru
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'themes/default', media: 'all', 'data-turbolinks-track'=>true
    = javascript_include_tag 'application', 'data-turbolinks-track'=>true
    = csrf_meta_tags
  body
    include _header.html.slim
    #container
      #content
        = yield
    #footer
      small
        | Served by
        =<> Socket.gethostname
        =<> render_time

app/views/layouts/image.html.slim
doctype html
html
  head
    title
      | #{@image.id_number} - Litebooru
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'themes/default', media: 'all', 'data-turbolinks-track'=>true
    = javascript_include_tag 'application', 'data-turbolinks-track'=>true
    = csrf_meta_tags
  body
    include _header.html.slim
    #container
      #sidebar
        #interactions
          span.fave-link
            a> href="/"
              => @image.favourites
              i.fa.fa-star
          span.upvote-link
            a> href="/"
              => @image.up_vote_count
              i.fa.fa-arrow-up
          strong=<> @image.score
          span.downvote-link
            a> href="/"
              i.fa.fa-arrow-down>
              = @image.down_vote_count
          span.comments-link
            a> href="#comments"
              i.fa.fa-comments>
              = @image.comments.count
        #image-uploader
          | Uploaded
          =<> friendly_time(@image.created_at)
          | by
          br
          b= link_to_author(@image)
        #image-size
          - size_kb = @image.image.size/1024
          - size_mb = (size_kb/1024.0).round(2)
          strong=> "#{@image.dimensions}"
          = File.extname(@image.image.path).upcase
          br
          - if size_kb <= 1024
            = "#{size_kb} kB "
          - else
            span title="#{size_kb} kB" ="#{size_mb} MB "
        #image-previews
          
      #content.content-right
        = yield
    #footer
      small
        | Served by
        =<> Socket.gethostname
        =<> render_time